/*
 * PresumeStmtRule.java
 * ---------------------------------
 * Copyright (c) 2024
 * RESOLVE Software Research Group
 * School of Computing
 * Clemson University
 * All rights reserved.
 * ---------------------------------
 * This file is subject to the terms and conditions defined in
 * file 'LICENSE.txt', which is part of this source code package.
 */
package edu.clemson.rsrg.vcgeneration.proofrules.statements;

import edu.clemson.rsrg.absyn.statements.AssumeStmt;
import edu.clemson.rsrg.absyn.statements.ConfirmStmt;
import edu.clemson.rsrg.absyn.statements.PresumeStmt;
import edu.clemson.rsrg.parsing.data.LocationDetailModel;
import edu.clemson.rsrg.vcgeneration.proofrules.AbstractProofRuleApplication;
import edu.clemson.rsrg.vcgeneration.proofrules.ProofRuleApplication;
import edu.clemson.rsrg.vcgeneration.utilities.AssertiveCodeBlock;
import edu.clemson.rsrg.vcgeneration.utilities.VerificationContext;
import org.stringtemplate.v4.ST;
import org.stringtemplate.v4.STGroup;

/**
 * <p>
 * This class contains the logic for applying the {@code presume} rule.
 * </p>
 *
 * @author Yu-Shan Sun
 *
 * @version 1.0
 */
public class PresumeStmtRule extends AbstractProofRuleApplication implements ProofRuleApplication {

    // ===========================================================
    // Member Fields
    // ===========================================================

    /**
     * <p>
     * The {@link PresumeStmt} we are applying the rule to.
     * </p>
     */
    private final PresumeStmt myPresumeStmt;

    // ===========================================================
    // Constructors
    // ===========================================================

    /**
     * <p>
     * This creates a new application of the {@code presume} rule.
     * </p>
     *
     * @param presumeStmt
     *            The {@link PresumeStmt} we are applying the rule to.
     * @param block
     *            The assertive code block that the subclasses are applying the rule to.
     * @param context
     *            The verification context that contains all the information we have collected so far.
     * @param stGroup
     *            The string template group we will be using.
     * @param blockModel
     *            The model associated with {@code block}.
     */
    public PresumeStmtRule(PresumeStmt presumeStmt, AssertiveCodeBlock block, VerificationContext context,
            STGroup stGroup, ST blockModel) {
        super(block, context, stGroup, blockModel);
        myPresumeStmt = presumeStmt;
    }

    // ===========================================================
    // Public Methods
    // ===========================================================

    /**
     * <p>
     * This method applies the {@code Proof Rule}.
     * </p>
     */
    @Override
    public final void applyRule() {
        // Add a new confirm statement followed by an assume statement
        // generated by the presume statement to the assertive code block.
        // YS: We clone the location and expression to avoid aliasing.
        myPresumeStmt.getAssertion().setLocationDetailModel(new LocationDetailModel(myPresumeStmt.getLocation().clone(),
                myPresumeStmt.getLocation().clone(), "Presume Statement Assertion"));
        myCurrentAssertiveCodeBlock.addStatement(
                new ConfirmStmt(myPresumeStmt.getLocation().clone(), myPresumeStmt.getAssertion().clone(), false));
        myCurrentAssertiveCodeBlock.addStatement(
                new AssumeStmt(myPresumeStmt.getLocation().clone(), myPresumeStmt.getAssertion().clone(), false));

        // Add the different details to the various different output models
        ST stepModel = mySTGroup.getInstanceOf("outputVCGenStep");
        stepModel.add("proofRuleName", getRuleDescription()).add("currentStateOfBlock", myCurrentAssertiveCodeBlock);
        myBlockModel.add("vcGenSteps", stepModel.render());
    }

    /**
     * <p>
     * This method returns a description associated with the {@code Proof Rule}.
     * </p>
     *
     * @return A string.
     */
    @Override
    public final String getRuleDescription() {
        return "Presume Rule";
    }

}
