version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: daily
      time: "10:00"
    target-branch: "main"
    open-pull-requests-limit: 10
    reviewers:
      - yushan87
    labels:
      - dependencies
