#
# Continuous integration settings for Travis CI
#
dist: trusty
sudo: false
branches:
  only:
    - master

# Make sure we run most of the tests using JDK7, because the RESOLVE WebIDE-v4 does not
# support JDK8. However, some of our newer JUnit tests require JDK8, so we need to include
# both versions and call "jdk_switcher" accordingly.
language: java
jdk:
  - oraclejdk8
  - oraclejdk7

# Don't run the initial maven install
install: true

# The following settings allow us to run concurrent tests using the scripts in the "bin" folder.
# It also caches things related to Maven. If caching errors occur, please clear the cache on the
# Travis CI website.
env:
  - SCRIPT_JDK7=runFormatter
  - SCRIPT_JDK7=runLicensePlugin
  - SCRIPT_JDK7=runCompilerTests
  - SCRIPT_JDK8=runJUnitTests
before_script:
  - chmod +x bin/$SCRIPT_JDK7
  - chmod +x bin/$SCRIPT_JDK8
script:
  - jdk_switcher use oraclejdk7
  - bin/$SCRIPT_JDK7
  - jdk_switcher use oraclejdk8
  - bin/$SCRIPT_JDK8
cache:
  directories:
      - $HOME/.m2