#
# Continuous integration settings for Travis CI
#
dist: trusty
sudo: false
branches:
  only:
    - master

# Use JDK8
language: java
jdk: oraclejdk8
  
# Skipping the Installation Step and Run Unit Tests
install: true
cache:
  directories:
    - $HOME/.m2

# The following settings allow us to run concurrent tests using the scripts in the "bin" folder.
# It also caches things related to Maven. If caching errors occur, please clear the cache on the
# Travis CI website.
jobs:
  include:
    - stage: check styles
      jdk: oraclejdk8
      before_script:
        - chmod +x bin/runFormatter
      script:
        - bin/runFormatter
    - stage: check styles
      jdk: oraclejdk8
      before_script:
        - chmod +x bin/runLicensePlugin
      script:
        - bin/runLicensePlugin
    - stage: compiler tests
      jdk: oraclejdk8
      install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      env:
        - SCRIPT=runAnalyzeTests
        - SCRIPT=runProveTests
      before_script: chmod +x bin/$SCRIPT
      script: bin/$SCRIPT