#
# Continuous integration settings for Travis CI
#
dist: trusty
sudo: false
branches:
  only:
    - master

# Compile and run the tests using JDK8
language: java
jdk:
  - oraclejdk8

# The following settings allow us to run concurrent tests using the scripts in the "bin" folder.
# It also caches things related to Maven. If caching errors occur, please clear the cache on the
# Travis CI website.
jobs:
  include:
    - stage: test
      install: skip
      script: mvn test
    - stage: checkStyles
      install: skip
      before_script:
        - chmod +x bin/runFormatter
      script:
        - bin/runFormatter
    - stage: checkStyles
      install: skip
      before_script:
        - chmod +x bin/runLicensePlugin
      script:
        - bin/runLicensePlugin
    - stage: compiler tests
        - SCRIPT=runCompilerTests
      install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      before_script: chmod +x bin/runCompilerTests
      script: bin/runCompilerTests
      cache:
        directories:
          - $HOME/.m2