#
# Continuous integration settings for Travis CI
#
dist: trusty
sudo: false
branches:
  only:
    - master

# Compile and run the tests using JDK8
language: java
jdk: oraclejdk8
  
# Skipping the Installation Step
install: true

# The following settings allow us to run concurrent tests using the scripts in the "bin" folder.
# It also caches things related to Maven. If caching errors occur, please clear the cache on the
# Travis CI website.
jobs:
  include:
    - stage: check styles
      jdk: oraclejdk8
      env:
        - SCRIPT=runFormatter
        - SCRIPT=runLicensePlugin
      before_script:
        - chmod +x bin/$SCRIPT
      script:
        - bin/$SCRIPT
    - stage: compiler tests
      before_script: chmod +x bin/runCompilerTests
      script: bin/runCompilerTests
      cache:
        directories:
          - $HOME/.m2