package edu.clemson.cs.r2jt.vcgeneration;

/*
 * Libraries
 */
import java.util.Date;

/**
 * TODO: Write a description of this module
 */
public class VerboseOutput {

    // ===========================================================
    // Global Variables 
    // ===========================================================

    /*
     * Name of File
     */
    private String myFileName;
    /*
     * Verbose String Buffer
     */
    private StringBuffer myVCBuffer;

    // ===========================================================
    // Constructors
    // ===========================================================
    public VerboseOutput(String fileName) {
        myFileName = fileName;

        /*
         * Build the header
         */
        buildHeaderComment();
    }

    // ===========================================================
    // Mutator/Accessor Methods
    // ===========================================================
    // -----------------------------------------------------------
    // Get Methods
    // -----------------------------------------------------------
    // -----------------------------------------------------------
    // Set Methods
    // -----------------------------------------------------------	
    // ===========================================================
    // Public Methods
    // ===========================================================
    public void buildConceptName(String conceptName) {
        myVCBuffer.append("Concept Name: ");
        myVCBuffer.append(conceptName);
        myVCBuffer.append("\n");
    }

    // ===========================================================
    // Private Methods
    // ===========================================================
    /**
     * Builds a comment header to identify VC files generated by the compiler
     * and from which Resolve source file the generated file is derived.
     */
    private void buildHeaderComment() {
        String header =
                "//\n"
                        + "// Generated by the RESOLVE VCGenerator, March 2012 version"
                        + "\n" + "// from file:  " + myFileName + "\n"
                        + "// on:         " + new Date() + "\n" + "//\n";
        myVCBuffer.append(header);
    }
}