package edu.clemson.cs.r2jt.absyn;

public class FlexibleVisitor<R, P> {

	public R visitAssumeStmt(AssumeStmt data, P parameter) { return null; }
	public R visitAuxCodeStmt(AuxCodeStmt data, P parameter) {return null;}
    public R visitDoubleExp(DoubleExp data, P parameter) {return null; }
    public R visitBetweenExp(BetweenExp data, P parameter) {return null; }
    public R visitAlternativeExp(AlternativeExp data, P parameter) {return null; }
    public R visitAuxVarDec(AuxVarDec data, P parameter) {return null; }
    public R visitProgramFunctionExp(ProgramFunctionExp data, P parameter) {return null; }
    public R visitFinalItem(FinalItem data, P parameter) {return null; }
    public R visitCharExp(CharExp data, P parameter) {return null; }
    public R visitConfirmStmt(ConfirmStmt data, P parameter) { return null;}
    public R visitTupleTy(TupleTy data, P parameter) {return null; }
    public R visitConceptTypeParamDec(ConceptTypeParamDec data, P parameter) {return null; }
    public R visitIfStmt(IfStmt data, P parameter) { return null;}
    public R visitOperationDec(OperationDec data, P parameter) { return null;}
    public R visitDotExp(DotExp data, P parameter) { return null;}
    public R visitPrefixExp(PrefixExp data, P parameter) {return null; }
    public R visitFunctionExp(FunctionExp data, P parameter) {return null; }
    public R visitOldExp(OldExp data, P parameter) {return null; }
    public R visitEnhancementBodyModuleDec(EnhancementBodyModuleDec data, 
    		P parameter) { return null;}
    public R visitProgramDoubleExp(ProgramDoubleExp data, P parameter) {return null; }
    public R visitMemoryStmt(MemoryStmt data, P parameter) {return null; }
    public R visitWhileStmt(WhileStmt data, P parameter) {return null; }
    public R visitVarDec(VarDec data, P parameter) {return null; }
    public R visitIterateExitStmt(IterateExitStmt data, P parameter) {return null; }
    public R visitIntegerExp(IntegerExp data, P parameter) { return null;}
    public R visitCartProdTy(CartProdTy data, P parameter) {return null; }
    public R visitRealizationParamDec(RealizationParamDec data, P parameter) {return null; }
    public R visitMathTypeDec(MathTypeDec data, P parameter) {return null; }
    public R visitSwapStmt(SwapStmt data, P parameter) {return null; }
    public R visitFacilityTypeDec(FacilityTypeDec data, P parameter) {return null; }
    public R visitProgramDotExp(ProgramDotExp data, P parameter) {return null; }
    public R visitParameterVarDec(ParameterVarDec data, P parameter) { return null;}
    public R visitEqualsExp(EqualsExp data, P parameter) {return null; }
    public R visitConceptBodyModuleDec(ConceptBodyModuleDec data, P parameter) { return null;}
    public R visitProgramIntegerExp(ProgramIntegerExp data, P parameter) {return null; }
    public R visitProgramCharExp(ProgramCharExp data, P parameter) {return null; }
    public R visitProgramStringExp(ProgramStringExp data, P parameter) {return null; }
    public R visitQuantExp(QuantExp data, P parameter) {return null; }
    public R visitStringExp(StringExp data, P parameter) {return null; }
    public R visitDefinitionDec(DefinitionDec data, P parameter) {return null; }
    public R visitLambdaExp(LambdaExp data, P parameter) { return null;}
    public R visitFacilityDec(FacilityDec data, P parameter) { return null;}
    public R visitArrayTy(ArrayTy data, P parameter) {return null; }
    public R visitIterativeExp(IterativeExp data, P parameter) {return null; }
    public R visitSetExp(SetExp data, P parameter) { return null;}
    public R visitMathVarDec(MathVarDec data, P parameter) { return null;}
    public R visitVariableNameExp(VariableNameExp data, P parameter) { return null;}
    public R visitIterateStmt(IterateStmt data, P parameter) {return null; }
    public R visitSelectionStmt(SelectionStmt data, P parameter) {return null; }
    public R visitVarExp(VarExp data, P parameter) {return null; }
    public R visitFunctionArgList(FunctionArgList data, P parameter) {return null; }
    public R visitProgramParamExp(ProgramParamExp data, P parameter) {return null; }
    public R visitFacilityOperationDec(FacilityOperationDec data, P parameter) { return null;}
    public R visitConstantParamDec(ConstantParamDec data, P parameter) { return null;}
    public R visitAltItemExp(AltItemExp data, P parameter) {return null; }
    public R visitTypeFunctionExp(TypeFunctionExp data, P parameter) { return null;}
    public R visitModuleArgumentItem(ModuleArgumentItem data, P parameter) { return null;}
    public R visitAffectsItem(AffectsItem data, P parameter) { return null;}
    public R visitProgramOpExp(ProgramOpExp data, P parameter) {return null; }
    public R visitVariableRecordExp(VariableRecordExp data, P parameter) { return null;}
    public R visitMathTypeFormalDec(MathTypeFormalDec data, P parameter) { return null;}
    public R visitChoiceItem(ChoiceItem data, P parameter) {return null; }
    public R visitEnhancementModuleDec(EnhancementModuleDec data, P parameter) {return null; }
    public R visitFieldExp(FieldExp data, P parameter) {return null; }
    public R visitNameTy(NameTy data, P parameter) {return null; }
    public R visitVariableDotExp(VariableDotExp data, P parameter) {return null; }
    public R visitUnaryMinusExp(UnaryMinusExp data, P parameter) {return null; }
    public R visitTupleExp(TupleExp data, P parameter) {return null; }
    public R visitCallStmt(CallStmt data, P parameter) {return null; }
    public R visitEnhancementBodyItem(EnhancementBodyItem data, P parameter) { return null;}
    public R visitOutfixExp(OutfixExp data, P parameter) {return null; }
    public R visitProcedureDec(ProcedureDec data, P parameter) {return null; }
    public R visitRenamingItem(RenamingItem data, P parameter) { return null;}
    public R visitMathAssertionDec(MathAssertionDec data, P parameter) { return null;}
    public R visitRepresentationDec(RepresentationDec data, P parameter) { return null;}
    public R visitConceptModuleDec(ConceptModuleDec data, P parameter) {return null; }
    public R visitFacilityModuleDec(FacilityModuleDec data, P parameter) { return null;}
    public R visitConditionItem(ConditionItem data, P parameter) {return null; }
    public R visitUsesItem(UsesItem data, P parameter) { return null;}
    public R visitFuncAssignStmt(FuncAssignStmt data, P parameter) {return null; }
    public R visitEnhancementItem(EnhancementItem data, P parameter) { return null;}
    public R visitInitItem(InitItem data, P parameter) {return null; }
    public R visitShortFacilityModuleDec(ShortFacilityModuleDec data, P parameter) {return null; }
    public R visitVariableArrayExp(VariableArrayExp data, P parameter) {return null; }
    public R visitMathModuleDec(MathModuleDec data, P parameter) {return null; }
    public R visitConstructedTy(ConstructedTy data, P parameter) {return null; }
    public R visitTypeDec(TypeDec data, P parameter) { return null;}
    public R visitFunctionTy(FunctionTy data, P parameter) { return null;}
    public R visitInfixExp(InfixExp data, P parameter) {return null; }
    public R visitIfExp(IfExp data, P parameter) {return null; }
    public R visitRecordTy(RecordTy data, P parameter) {return null; }
    public R visitGoalExp(GoalExp data, P parameter) {return null; }
    public R visitSuppositionExp(SuppositionExp data, P parameter) { return null;}
    public R visitDeductionExp(DeductionExp data, P parameter) {return null; }
    public R visitSuppositionDeductionExp(SuppositionDeductionExp data, P parameter) {return null; }
    public R visitProofDec(ProofDec data, P parameter) {return null; }
    public R visitProofDefinitionExp(ProofDefinitionExp data, P parameter) { return null;}
    public R visitProofModuleDec(ProofModuleDec data, P parameter) {return null; }
    public R visitJustifiedExp(JustifiedExp data, P parameter) {return null; }
    public R visitJustificationExp(JustificationExp data, P parameter) { return null;}
    public R visitHypDesigExp(HypDesigExp data, P parameter) { return null;}
    public R visitMathRefExp(MathRefExp data, P parameter) {return null; }
    public R visitSubtypeDec(SubtypeDec data, P parameter) {return null; }
}