/*
 * VerificationCondition.java
 * ---------------------------------
 * Copyright (c) 2017
 * RESOLVE Software Research Group
 * School of Computing
 * Clemson University
 * All rights reserved.
 * ---------------------------------
 * This file is subject to the terms and conditions defined in
 * file 'LICENSE.txt', which is part of this source code package.
 */
package edu.clemson.cs.rsrg.vcgeneration.utilities;

import edu.clemson.cs.rsrg.parsing.data.BasicCapabilities;
import edu.clemson.cs.rsrg.parsing.data.Location;
import edu.clemson.cs.rsrg.parsing.data.LocationDetailModel;
import edu.clemson.cs.rsrg.vcgeneration.sequents.Sequent;
import java.util.ArrayList;
import java.util.List;

/**
 * <p>This class represents a possibly-named {@code verification condition} ({@code VC})
 * with a list of associated {@link Sequent Sequents}.</p>
 *
 * <p>When proving a {@link VerificationCondition}, only one of the associated {@link Sequent}
 * needs to be {@code true}. This is because the associated {@link Sequent Sequents} share
 * one or more {@code consequents}. This means that proving one of the {@link Sequent} is
 * good enough for us.</p>
 *
 * @author Yu-Shan Sun
 * @version 1.0
 */
public class VerificationCondition implements BasicCapabilities, Cloneable {

    // ===========================================================
    // Member Fields
    // ===========================================================

    /**
     * <p>List of {@link Sequent Sequents} associated with
     * this {@code VC}.</p>
     */
    private final List<Sequent> myAssociatedSequents;

    /**
     * <p>A flag that indicates whether or not this {@link VerificationCondition}
     * contains a {@link Sequent} that had an impacting reduction.</p>
     */
    private final boolean myHasImpactingReduction;

    /** <p>The location for this {@code Sequent}.</p> */
    private Location myLocation;

    /**
     * <p>An object that contains additional information on why the {@code VCGenerator}
     * generated this {@code VC}. This model should come from the expressions that where
     * generated by applying the various different {@code proof rules}.</p>
     */
    private final LocationDetailModel myLocationDetailModel;

    /** <p>Name given to the {@code VC}.</p> */
    private final String myName;

    // ===========================================================
    // Constructors
    // ===========================================================

    /**
     * <p>This creates a {@code VC} with a name and associated
     * {@link Sequent Sequents}.</p>
     *
     * @param loc The location that created this {@code VC}.
     * @param name Name given to this {@code VC}.
     * @param sequents List of {@link Sequent Sequents}
     *                 associated with this {@code VC}.
     * @param hasImpactingReduction A flag that indicates whether or not
     *                              this {@code VC} had an impacting reduced
     *                              {@link Sequent}.
     * @param model The {@link LocationDetailModel} associated with
     *              this {@code VC}.
     */
    public VerificationCondition(Location loc, String name,
            List<Sequent> sequents, boolean hasImpactingReduction,
            LocationDetailModel model) {
        myAssociatedSequents = sequents;
        myHasImpactingReduction = hasImpactingReduction;
        myLocation = loc;
        myLocationDetailModel = model;
        myName = name;
    }

    /**
     * <p>This creates a nameless {@code VC} with the associated
     * {@link Sequent Sequents}.</p>
     *
     * @param loc The location that created this {@code VC}.
     * @param sequents List of {@link Sequent Sequents}
     *                 associated with this {@code VC}.
     * @param hasImpactingReduction A flag that indicates whether or not
     *                              this {@code VC} had an impacting reduced
     *                              {@link Sequent}.
     * @param model The {@link LocationDetailModel} associated with
     *              this {@code VC}.
     */
    public VerificationCondition(Location loc, List<Sequent> sequents,
            boolean hasImpactingReduction, LocationDetailModel model) {
        this(loc, null, sequents, hasImpactingReduction, model);
    }

    // ===========================================================
    // Public Methods
    // ===========================================================

    /**
     * <p>This method creates a special indented
     * text version of the instantiated object.</p>
     *
     * @param indentSize The base indentation to the first line
     *                   of the text.
     * @param innerIndentInc The additional indentation increment
     *                       for the subsequent lines.
     *
     * @return A formatted text string of the class.
     */
    @Override
    public final String asString(int indentSize, int innerIndentInc) {
        StringBuilder sb = new StringBuilder();

        for (Sequent sequent : myAssociatedSequents) {
            sb.append(sequent.asString(indentSize, innerIndentInc));
            sb.append("\n");
        }

        return sb.toString();
    }

    /**
     * <p>This method overrides the default {@code clone} method implementation.</p>
     *
     * @return A deep copy of the object.
     */
    @Override
    public final VerificationCondition clone() {
        // YS: Collections.copy complains about source does not fit in dest,
        // so we manually copy everything.
        List<Sequent> copySequents = new ArrayList<>(myAssociatedSequents.size());
        for (Sequent s : myAssociatedSequents) {
            copySequents.add(s.clone());
        }

        return new VerificationCondition(myLocation.clone(), myName,
                copySequents, myHasImpactingReduction,
                myLocationDetailModel.clone());
    }

    /**
     * <p>This method overrides the default {@code equals} method implementation.</p>
     *
     * @param o Object to be compared.
     *
     * @return {@code true} if all the fields are equal, {@code false} otherwise.
     */
    @Override
    public final boolean equals(Object o) {
        if (this == o)
            return true;
        if (o == null || getClass() != o.getClass())
            return false;

        VerificationCondition that = (VerificationCondition) o;

        return myHasImpactingReduction == that.myHasImpactingReduction
                && myAssociatedSequents.equals(that.myAssociatedSequents)
                && myLocation.equals(that.myLocation)
                && myLocationDetailModel.equals(that.myLocationDetailModel)
                && (myName != null ? myName.equals(that.myName)
                        : that.myName == null);
    }

    /**
     * <p>This method returns the list of {@code sequents} stored inside
     * this {@code VC}.</p>
     *
     * @return A list of {@link Sequent Sequents}.
     */
    public final List<Sequent> getAssociatedSequents() {
        return myAssociatedSequents;
    }

    /**
     * <p>This method indicates if the {@link VerificationCondition} contains
     * a {@link Sequent} that had an impacting reduction or not.</p>
     *
     * @return {@code true} if we have applied some kind of logical
     * reduction to one of the associated {@link Sequent Sequents},
     * {@code false} otherwise.
     */
    public final boolean getHasImpactingReductionFlag() {
        return myHasImpactingReduction;
    }

    /**
     * <p>This method returns the location that created
     * this {@code VC}.</p>
     *
     * @return A {@link Location}.
     */
    public final Location getLocation() {
        return myLocation;
    }

    /**
     * <p>This method gets the location details associated
     * with this {@code VC}.</p>
     *
     * @return A {@link LocationDetailModel}.
     */
    public final LocationDetailModel getLocationDetailModel() {
        return myLocationDetailModel;
    }

    /**
     * <p>This method returns the name for this {@code VC}.</p>
     *
     * @return A string.
     */
    public final String getName() {
        return myName;
    }

    /**
     * <p>This method overrides the default {@code hashCode} method implementation.</p>
     *
     * @return The hash code associated with the object.
     */
    @Override
    public final int hashCode() {
        int result = myAssociatedSequents.hashCode();
        result = 31 * result + (myHasImpactingReduction ? 1 : 0);
        result = 31 * result + myLocation.hashCode();
        result = 31 * result + myLocationDetailModel.hashCode();
        result = 31 * result + (myName != null ? myName.hashCode() : 0);
        return result;
    }

    /**
     * <p>This method returns the object in string format.</p>
     *
     * @return Object as a string.
     */
    @Override
    public final String toString() {
        return asString(0, 4);
    }

}